export const ACTION_TYPE = {
	SET_USER: 'SET_USER',

	SET_PRODUCTS: 'SET_PRODUCTS',
	UPDATE_PRODUCTS: 'UPDATE_PRODUCTS',

	SET_PRODUCT_DATA: 'SET_PRODUCT_DATA',
	RESET_PRODUCT_DATA: 'RESET_PRODUCT_DATA',
	SEARCH_PRODUCT: 'SEARCH_PRODUCT',
	CHANGE_SEARCH_TERM: 'CHANGE_SEARCH_TERM',
	SORT_PRODUCT: 'SORT_PRODUCT',
	REMOVE_PRODUCT: 'REMOVE_PRODUCT',

	ADD_REVIEW: 'ADD_REVIEW',
	REMOVE_REVIEW: 'REMOVE_REVIEW',
	SET_REVIEWS: 'SET_REVIEWS',

	ADD_COMMENT: 'ADD_COMMENT',
	REMOVE_COMMENT: 'REMOVE_COMMENT',

	IS_LOADING: 'IS_LOADING',
	LOGOUT: 'LOGOUT',

	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',

	ADD_TO_CART: 'ADD_TO_CART',
	REMOVE_FROM_CART: 'REMOVE_FROM_CART',
	ADD_COUNT: 'ADD_COUNT',
	SUB_COUNT: 'SUB_COUNT',
	CLEAR_CART: 'CLEAR_CART',
	SET_CART: 'SET_CART',

	SET_PURCHASE_DATA: 'SET_PURCHASE_DATA',
};
