export * from './about-us/AboutUs';
export * from './authorization/Authorization';
export * from './main/Main';
export * from './personal-cabinet/PersonalCabinet';
export * from './product/Product';
export * from './products/Products';
export * from './registration/Registration';
export * from './reviews/Reviews';
export * from './cart/Cart';
